[book]
authors = ["SkyBlockDev"]
language = "en"
multilingual = false
src = "src"
title = "SkyBlockDev"
default-theme = "Rust"
git-repository-url = "https://github.com/SkyBlockDev/skyblockdev.github.io"