name: Deploy the fucking website
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - uses: actions/checkout@v1
      - uses: c-hive/gha-yarn-cache@v2
      - run: yarn install
      - run: yarn export
      - run: echo "tricked.is-a.dev" > CNAME
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./out
